package lt.vu.usecases.mybatis.model;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Job {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.jobs.id
     *
     * @mbg.generated Sun Apr 07 16:25:19 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.jobs.title
     *
     * @mbg.generated Sun Apr 07 16:25:19 EEST 2019
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.jobs.id
     *
     * @return the value of public.jobs.id
     *
     * @mbg.generated Sun Apr 07 16:25:19 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.jobs.id
     *
     * @param id the value for public.jobs.id
     *
     * @mbg.generated Sun Apr 07 16:25:19 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.jobs.title
     *
     * @return the value of public.jobs.title
     *
     * @mbg.generated Sun Apr 07 16:25:19 EEST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.jobs.title
     *
     * @param title the value for public.jobs.title
     *
     * @mbg.generated Sun Apr 07 16:25:19 EEST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }
}