package lt.vu.usecases.mybatis.dao;

import java.util.List;
import lt.vu.usecases.mybatis.model.Firm;
import org.mybatis.cdi.Mapper;

@Mapper
public interface FirmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.firms
     *
     * @mbg.generated Sun Apr 07 16:25:19 EEST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.firms
     *
     * @mbg.generated Sun Apr 07 16:25:19 EEST 2019
     */
    int insert(Firm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.firms
     *
     * @mbg.generated Sun Apr 07 16:25:19 EEST 2019
     */
    Firm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.firms
     *
     * @mbg.generated Sun Apr 07 16:25:19 EEST 2019
     */
    List<Firm> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.firms
     *
     * @mbg.generated Sun Apr 07 16:25:19 EEST 2019
     */
    int updateByPrimaryKey(Firm record);
}